export default async function Techs(req, res) {
    res.json([
        [ "JavaScript", "javascript.png" ],
        [ "TypeScript", "typescript.png" ],
        [ "Node.js", "nodejs.png" ],
        [ "Discord.js", "discordjs.png" ],
        [ "HTML", "html.png" ],
        [ "CSS", "css.png" ],
        [ "Angular", "angular.png" ],
        [ "React", "react.png" ],
        [ "Next.js", "nextjs.png" ],
        [ "Nuxt.js", "nuxtjs.png" ],
        [ "Vue.js", "vuejs.png" ],
        [ "Vite", "vite.png" ],
        [ "Bootstrap", "bootstrap.png" ],
        [ "Electron.js", "electronjs.png" ],
        [ "Express.js", "expressjs.png" ],
        [ "Tailwind CSS", "tailwindcss.png" ],
        [ "Sass", "sass.png" ],
        [ "Webpack", "webpack.png" ],
        [ "Lua", "lua.png" ],
        [ "qbCore", "qbcore.png" ],
        [ "php", "php.png" ],
        [ "MySQL", "mysql.png" ],
        [ "HeidiSQL", "heidisql.png" ],
        [ "Python", "python.png" ],
        [ "Java", "java.png" ],
        [ "C", "c.png" ],
        [ "C++", "cpp.png" ],
        [ "C#", "csharp.png" ],
        [ "Supabase", "supabase.png" ],
        [ "MongoDB", "mongodb.png" ],
        [ "Firebase", "firebase.png" ],
        [ "Figma", "figma.png" ],
        [ "Framer", "framer.png" ],
        [ "Google Fonts", "googlefonts.png" ],
        [ "Font Awesome", "fontawesome.png" ],
        [ "IconScout", "iconscout.png" ],
        [ "Icons8", "icons8.png" ],
        [ "Git", "git.png" ],
        [ "Github", "github.png" ],
        [ "Stack Overflow", "stackoverflow.png" ],
        [ "dockerfile", "dockerfile.png" ],
        [ "yarn", "yarn.png" ],
        [ "npm", "npm.png" ],
        [ "Google Cloud", "googlecloud.png" ],
        [ "CloudFlare", "cloudflare.png" ],
        [ "Vercel", "vercel.png" ],
        [ "Repl.it", "replit.png" ],
        [ "Netlify", "netlify.png" ],
        [ "XAMPP", "xampp.png" ],
        [ "Laragon", "laragon.png" ],
        [ "ngrok", "ngrok.png" ],
        [ "Uptimerobot", "uptimerobot.png" ],
        [ "v0", "v0.png" ],
        [ "bolt", "bolt.png" ],
        [ "same", "same.png" ],
        [ "OpenAI", "openai.png" ],
        [ "Grok", "grok.png" ],
        [ "Gemini", "gemini.png" ],
        [ "Copilot", "copilot.png" ],
        [ "LeonardoAI", "leonardoai.png" ],
        [ "Android Studio Code", "asc.png" ],
        [ "Cursor", "cursor.png" ],
        [ "Visual Studio Code", "vsc.png" ],
        [ "Visual Studio 2019", "vs2019.png" ],
        [ "Visual Studio 2022", "vs2022.png" ],
    ]);
};
